### ISSUE TITLE
No TXSS secretion system predicted

### ISSUE THREAD

**Issue by yjiakang** [gem-pasteur/macsyfinder#24]
when I want to predict the secretion system in a bacteria genome, I downloaded it's genome from NCBI genome with the fasta format of protein. Then I run: 
macsyfinder --db-type ordered_replicon --sequence-db ecoli.faa -o ecoli_result all
However, no TXSS (i.e. T3SS T6SS) in the results.macsyfinder.json file.
Anyone know about this?

**Comment by saphia** [comment]
How to report a bug?
====================

If you encounter a problem while running MacSyFinder, please submit an issue on the [dedicated page of the GitHub project](https://github.com/gem-pasteur/macsyfinder/issues). 

In order to ensure we have all elements to help, please provide: 

- a concise description of the issue
- the expected behavior VS observed one
- the exact command-line used 
- the version of MacSyFinder used
- the exact error message, and if applicable, the `macsyfinder.log` and `macsyfinder.conf` files
- if applicable, an archive (or link to it) with the output files obtained
- if possible, the smallest dataset there is to reproduce the issue
- if applicable, this would also include the macsy-models (XML models plus HMM profiles) used (or precise version of the models if there are publicly available). Same as above, if possible, please provide the smallest set possible of models and HMM profiles. 

All these will definitely help us to help you! ;-)
